import Head from 'next/head'
import Image from 'next/image'
import Slider from '../components/Slider'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
// import Banner from '../components/Banner'

export default function Home({}) {
  
  // const hasBanner = banner && Object.keys(banner).length > 0
  return (
    <div className='relative'>
      <Head>
        <title>Pinta bendita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Banner banner={banner}> */}

      <Header />
      <Slider/>
      {/* </Banner> */}
    </div>
  )
}
