import Head from 'next/head'
import Image from 'next/image'
import Slider from '../components/Slider'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Pinta bendita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slider/>
    </div>
  )
}
