import Head from 'next/head'
import Image from 'next/image'
import SwiperSlider from '../components/SwiperSlider'
import Header from '../components/Header'
import Modal from '../components/Modal'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import {openModal} from '../slices/modal/modalSlice'
import  {RootState} from '../store'
import axios from "axios";


export default function Home({}) {

  // useEffect(() => {


  // }, [])

  const {isOpen} = useSelector((state: RootState) => state.modal)
  const {isAuth} = useSelector((state: RootState) => state.auth)
console.log(isAuth)

  
  
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Pinta bendita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />
      {isOpen && <Modal /> }
      {isAuth && <SwiperSlider/> }

    </div>
  )
}
